config/routes.rb
Rails.application.routes.draw do
  
get 'homes/awesome_wedding_destinations_in_india'

  get 'homes/classic_wedding'

  get 'homes/wedding'

  get 'homes/corporate_events'

  

  get 'homes/view_more'

  
  get 'homes/flower_decoration'

  get 'homes/light_decoration'

  get 'homes/catering'

  get 'homes/view_all'

  get 'homes/indian'

  get 'homes/simply_stunning'

  get 'homes/moroccan'



  get 'homes/other_great_themes'

  get 'homes/blog'

  get 'homes/abouts'

  get 'homes/services'


  get 'homes/destination_wedding'

 

  get 'homes/index'
  root to: "homes#index" 
  resources :coffee_roasts
  resources :comments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee_roast.rb
class CoffeeRoast < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
def time
    created_at.strftime("%d/%m/%y at %l:%M %p")
end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coffee_roasts_controller.rb
class CoffeeRoastsController < ApplicationController
  before_action :set_coffee_roast, only: [:show, :edit, :update, :destroy]

  # GET /coffee_roasts
  # GET /coffee_roasts.json
  def index
    @coffee_roasts = CoffeeRoast.all
  end

  # GET /coffee_roasts/1
  # GET /coffee_roasts/1.json
  def show
  end

  # GET /coffee_roasts/new
  def new
    @coffee_roast = CoffeeRoast.new
  end

  # GET /coffee_roasts/1/edit
  def edit
  end

  # POST /coffee_roasts
  # POST /coffee_roasts.json
  def create

    @coffee_roast = CoffeeRoast.new(coffee_roast_params)
        account_sid = 'ACf2f5142ffa4e6436cfdb55e1f98bc122'
     auth_token = '6c5ab77c9110288fc301751a61c92966'
    @client = Twilio::REST::Client.new account_sid, auth_token
      message = "Hey here #{@coffee_roast.username}' was just added.,#{@coffee_roast.email_id},#{@coffee_roast.mobile_number},#{@coffee_roast.occasion}, #{@coffee_roast.query}"
     @client.api.account.messages.create(from: '+12162088447',to: '+918827047626',body: message )

    respond_to do |format|
      if @coffee_roast.save
        format.html { redirect_to new_coffee_roast_path, notice: 'Coffee roast was successfully created.' }
        format.json { render :new, status: :created, location: new_coffee_roast_path }
      else
        format.html { render :new }
        format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_roasts/1
  # PATCH/PUT /coffee_roasts/1.json
  def update
    respond_to do |format|
      if @coffee_roast.update(coffee_roast_params)
        format.html { redirect_to @coffee_roast, notice: 'Coffee roast was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee_roast }
      else
        format.html { render :edit }
        format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_roasts/1
  # DELETE /coffee_roasts/1.json
  def destroy
    @coffee_roast.destroy
    respond_to do |format|
      format.html { redirect_to coffee_roasts_url, notice: 'Coffee roast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_roast
      @coffee_roast = CoffeeRoast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_roast_params
      params.require(:coffee_roast).permit(:username, :query, :mobile_number, :email_id, :occasion)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
    @comments = Comment.all
  end

  def create
   @comment = Comment.new(comment_params)
     @comment.save
      redirect_to new_comment_path
  end

   def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
 
    redirect_to new_comment_path
  end
  private
  def comment_params
    params.require(:comment).permit(:name, :comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
  def awesome_wedding_destinations_in_india
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_roasts_helper.rb
module CoffeeRoastsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/coffee_roasts/edit.html.erb
<h1>Editing Coffee Roast</h1>

<%= render 'form', coffee_roast: @coffee_roast %>

<%= link_to 'Show', @coffee_roast %> |
<%= link_to 'Back', coffee_roasts_path %>

app/views/coffee_roasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Roasts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Query</th>
      <th>Mobile number</th>
      <th>Email</th>
      <th>Occasion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffee_roasts.each do |coffee_roast| %>
      <tr>
        <td><%= coffee_roast.username %></td>
        <td><%= coffee_roast.query %></td>
        <td><%= coffee_roast.mobile_number %></td>
        <td><%= coffee_roast.email_id %></td>
        <td><%= coffee_roast.occasion %></td>
        <td><%= link_to 'Show', coffee_roast %></td>
        <td><%= link_to 'Edit', edit_coffee_roast_path(coffee_roast) %></td>
        <td><%= link_to 'Destroy', coffee_roast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee Roast', new_coffee_roast_path %>

app/views/coffee_roasts/new.html.erb
<%= render 'form', coffee_roast: @coffee_roast %>

app/views/coffee_roasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @coffee_roast.username %>
</p>

<p>
  <strong>Query:</strong>
  <%= @coffee_roast.query %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @coffee_roast.mobile_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coffee_roast.email_id %>
</p>

<p>
  <strong>Occasion:</strong>
  <%= @coffee_roast.occasion %>
</p>

<%= link_to 'Edit', edit_coffee_roast_path(@coffee_roast) %> |
<%= link_to 'Back', coffee_roasts_path %>

app/views/comments/new.html.erb
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Great Vibes' rel='stylesheet'>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.mySlides {display:none;}
</style>
<body>
<div class="container-fluid">
<div class="row">
<div class="col-md-8">
<h2 style="text-align: left;margin-top: 5%;">
<span style="color: #ff48ff;">
 <i>Awesome Wedding Destinations in INDIA</i></span></h2>
<time id="" class="published" datetime="2018-01-11">January 11, 2018</time><br /><br />
<img src="https://media.publika.md/en/image/201610/full/indian-wedding-_84713100.jpg"  style="height: 400px; padding: 5px; width: 825px;"><br /><br />
</div>
<div class="col-md-4">
<!-- 1. classic wedding image part start -->
<h3 style="color: #c29e00; margin-top: 12%;margin-left: 10%;">Explore our Blog</h3><br />
<form novalidate="novalidate" class="col-sm-12" id="searchForm">
  
    <div class="form-group " style="width: 60%;margin-left: 6%;">
    <div class="row">
    
    <div class="col-md-10 col-xs-10" style="padding-right:0px"><div class="input-group input-group-lg center-block">
        <select aria-invalid="false" name="category" style="border-top-left-radius: 2em; border-bottom-left-radius: 2em;" class="form-control valid">
        <option><li><%= link_to "Awesome Wedding Destinations in INDIA",  homes_wedding_path, :mehtod=> 'get' %></li></option>
        </select>
        
      </div></div>
    <div class="col-md-2 col-xs-2" style="padding-left:0px"><div align="center"><button type="submit" class="btn btn-lg blue" style="border-top-right-radius: 2em; border-bottom-right-radius: 2em;transform:none;color:#FFFFFF;    border: 1px solid #3aa9a2;background: #3aa9a2"><span class="fa fa-search"></span>Search</button></div></div>
    </div>
    </div>
  </form>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-md-8">
<p class="lead" style="font-size:20px;color: black;"><p>Congratulations on finding your life partner! It must feel awesome. So now what? What comes next? Wedding planning……right!<br /><br />
You are surely thinking of some grand wedding ceremony. Well, its India. Wedding is a grand occasion for us afterall.<br /><br />
Of course you want a wedding away from the hectic busy life. A few days away from all the worries, A few days in peace. To achieve that, you need to choose the best destination.<br /><br />
A few of our grand India’s grand wedding destinations are-<br /><br />
<ul><li style="margin-left: 5%"><b style="color: #c29e00;">1. Udaipur (A symbol of royalty)-</b> If you wanna make your wedding day romantic and special, I hope the City of lakes would make your dream come true. Udaipur, the most loving and stunning place in Rajasthan is simply awesome for a traditional Indian wedding and so stands as one of the renowned Indian wedding destinations. The Leela, The Taj Lake Palace, and The Trident are some of the best options that you will like to enjoy being at. The architecture of this city perfectly blends innovation with tradition, offering the perfect backdrop for your dream wedding. So, choose from some of the exotic spots and have the day of your life.</li></ul>
</p><br/ >

<a target="_blank" href="https://www.i-escape.com/image/hotel/deogarh-mahal/overview/147585.jpg">
 <img src="https://www.i-escape.com/image/hotel/deogarh-mahal/overview/147585.jpg" alt="" style="height: 400px; padding: 5px; width: 825px;">
  </a><br />
<br />
<ul><li style="margin-left: 5%"><b style="color: #c29e00;">2. Jaipur (Royalty at your feet)-</b> The pink city of India is another famous destination for wedding. Offering a great heritage and beauty, this city is quite popular for extravagant wedding celebrations that always take place in palaces and mansions. The city itself showcases a complete combination of festive ideas and venue choices that hold out from palaces like Raj Palace, Gold Palace and Samode Palace. The city has so far solicited not only Indians but also the Hollywood celebrities too.</li></ul>
</p><br/ >

<a target="_blank" href="http://www.myweddingplanning.in/blog/wp-content/uploads/sites/11/wedding-at-city-palace-jaipur.jpg">
 <img src="http://www.myweddingplanning.in/blog/wp-content/uploads/sites/11/wedding-at-city-palace-jaipur.jpg" alt="" style="height: 400px; padding: 5px; width: 825px;">
  </a><br />
<br />
</div>
 </div>
 </div>

<div class="container-fluid">
<div class="row">
<div class="col-md-6">
<%= link_to '<button type="button" class="block" style="font-family: Verdana,sans-serif;margin-left: 0%;width: 20%;background-color: white;color: #2492ff; ">&laquo; previous</button>'.html_safe, homes_blog_path,style: "color: white",data: { turbolinks: false } %> 
 <!-- ending block button for classic wedding -->
<style>
.block {
    text-align: center;
    display: block;
    width: 20%;
    border: none;
    background-color: white;
    padding: 8px 15px;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    color: white
}
</style>
</div>
<div class="col-md-6">
<%= link_to '<button type="button" class="block" style="font-family: Verdana,sans-serif;margin-left: 75%;background-color: white;color: #2492ff;">Next &raquo;</button>'.html_safe, homes_blog_path,style: "color: white" %> 
 <!-- ending block button for classic wedding -->
<style>
.block {
    text-align: center;
    display: block;
    width: 20%;
    border: none;
    background-color: #48D1CC;
    padding: 5px 10px;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    color: white
}
</style>
<br />
</div>
</div>
</div>
<div class="col-md-12">
<div style="border-top:1px solid #0088cc;  color: #ff48ff;">
</div>
</div>

<div class="container-fluid">
<div class="row">
<div class="col-md-12">
  <!-- start the commnet form in html page !-->
<h3 style="color:  #ff48ff;margin-top: 5%;font-size: 1.618em;word-wrap: break-word;font-family: 'Great Vibes';font-size: 35px;text-align: center;">Leave a Reply</h3>
<p style="margin-top: 2%; color: black;margin-left: 5%;">
<ul style="margin-left: 4%; color: black;">
<h4 id="comment_count" style="color: #c29e00;"><%= pluralize(@comments.size, 'Comment') %></h4>
 <% @comments.each do |comment| %><br />
  <% if comment.comment %>
  <li>
  <span class="glyphicon glyphicon-user"></span>&nbsp;
   <strong style="color: #2492ff;"><%= comment.name %>&nbsp;</strong>     
     <%= comment.time %>&nbsp;&nbsp;&nbsp;&nbsp;<strong><%= link_to '<button type="button" style="background-color: white;color: #2492ff;">Delete</button>' .html_safe,  comment_path(comment),style: "color: white",
              method: :delete,
              data: { confirm: 'Are you sure?' } %></strong>
  
    <p style="margin-left: 2%;"><%= comment.comment %></p>

     </li>
   <% end %>
<% end %>
</ul>
<ul style="margin-left: 4%;">
<%= form_with scope: :comment, url:  comments_path, local: true do |f| %>
  <p>
    <%= f.text_field :name, autofocus: true, placeholder: "Your name" %></p>
    <p>
 <%= f.text_area :comment, autofocus: true, placeholder: "Your comment" %></p>
 <p>
 <p>
     <%= f.submit "Post Comment", :class => 'btn btn-primary', style: "background-color: #2492ff" %>
  </p>
<% end %>
</ul>
</p>
</div>
</div>
</div>
<div class="col-md-12">
<div style="border-top:3px solid #0088cc;  color: #ff48ff;margin-top: 2%;">
</div>
</div>

<!--Top button in footer code !-->
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
 
}
#myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: #2492ff;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}
#myBtn:hover {
  background-color: #555;
}
</style>
</head><body>
<button onclick="topFunction()" id="myBtn" title="Go to top">&#9650;</button>
<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};
function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}
// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>
<!--Top button in footer code !-->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RthApp</title>
    <!-- Second navbar for search -->
    <link href="application.css" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcvvgUncbNc_mOVwpa1gY6mxnvuWvEHlk &callback=initMap">
    </script>

</head>

  <body>
 <div id="nav" style="background-color: black;">
      <div id="nav_wrapper" style="background-color: black;color: white;">
      <ul>
      <li><%= link_to "Home" , homes_index_path, data: { turbolinks: false } %></li>
      <li><%= link_to "About Us", homes_abouts_path, data: { turbolinks: false } %></li>
      <!-- Event_Type  start page add -->
      <li><%= link_to "Event Types" %>
        <ul>
        <li><%= link_to "Weddings", homes_wedding_path, data: { turbolinks: false } %></li>
         <li><%= link_to "classic Wedding", homes_classic_wedding_path, data: { turbolinks: false } %></li>
        <li><%= link_to "Corporate Events", homes_corporate_events_path, data: { turbolinks: false } %></li>
        <li><%= link_to "View more",  homes_view_more_path, data: { turbolinks: false } %></li>
        </ul> 
      </li>
      <!-- Event_Type end page -->
      
      <!-- Services start page -->
      <li><%= link_to "Services" %>
        <ul>
        <li><%= link_to "Light Decoration", homes_light_decoration_path, data: { turbolinks: false } %></li>
        <li><%= link_to "Flower Decoration", homes_flower_decoration_path, data: { turbolinks: false } %></li>
        <li><%= link_to "Catering", homes_catering_path, data: { turbolinks: false } %></li>
        <li><%= link_to "View all", homes_view_all_path, data: { turbolinks: false } %></li>
        </ul>
      </li>
      <!-- Services end -->
      <!--- Gallery dropdown add -->
      <li><%= link_to "Themes" %>
        <ul>
      <li><%= link_to "Indian" , homes_indian_path, data: { turbolinks: false } %></li>
      <li><%= link_to "Simply Stunning", homes_simply_stunning_path, data: { turbolinks: false } %></li>
      <li><%= link_to "Moroccan", homes_moroccan_path, data: { turbolinks: false } %></li>
       <li><%= link_to "Other Great Themes", homes_other_great_themes_path, data: { turbolinks: false } %></li>
      </ul>
      </li>
      <!-- Gallery dropdown end -->
      <li><%= link_to "Destination Wedding", homes_destination_wedding_path, data: { turbolinks: false } %></li>
      <li><%= link_to "Blog", homes_blog_path, data: { turbolinks: false } %></li>

      <li><%= link_to "Contact Us", new_coffee_roast_path, data: { turbolinks: false } %></li>
      </ul>
    </div>
      </div>
     <div class="container-fluid">
     <%= image_tag "Product(7) edit.jpg" %>
     <i class="fa fa-phone" style="width: 20px;text-align: center;color: black;margin-left: 55%"></i>+91 8827047626 &nbsp;&nbsp;<i class="fa fa-phone" style="width: 20px;text-align: center;color: black;"></i>+91 9329282425
    </div><br />
   
    <%= yield %>
   
<!-- footer add page -->
<footer id="footer" class="narrow" style="background-color: black; padding-top: 30px;font-size: 0.9em;margin-top: 0px;position: relative;clear: both;border-top: 4px solid #060606;">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<link rel="stylesheet" href="style.css">
<div class="container">
<div class="row" style="margin-right: -15px;margin-left: -15px; margin-bottom: 25px;">

<div class="col-md-9" style="width: 75%;float: left;    position: relative;min-height: 1px;padding-right: 15px;
padding-left: 15px;
">

<ul class="nav nav-pills" style="padding-left: 0;margin-bottom: 0;list-style: none; float: left;">

<li>
<p style="line-height: 24px;padding: 5px 12px;color: white;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "About Us", homes_abouts_path,style: "color: white",data: { turbolinks: false } %></p>
</li>
<li>
<p style="line-height: 24px;padding: 5px 12px;color: #FFF;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "Privacy Policy","#",style: "color: white",data: { turbolinks: false } %></p>
</li>
<li>
<p style="line-height: 24px;padding: 5px 12px;color: #FFF;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "Term of Use","#",style: "color: white",data: { turbolinks: false } %></p>
</li>
<li>
<p style="line-height: 24px;padding: 5px 12px;color: #FFF;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "Home",  homes_index_path,style: "color: white",data: { turbolinks: false } %></p>
</li>
<li>
<p style="line-height: 24px;padding: 5px 12px;color: #FFF;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "Quick Enquiry","#",style: "color: white",data: { turbolinks: false } %></p>
</li>
<li>
<p style="line-height: 24px;padding: 5px 12px;color: #FFF;border-radius: 4px;position: relative;display: block;outline: none !important;text-decoration: none;background-color: transparent;box-sizing: border-box;"><%= link_to "Contact-Us",new_coffee_roast_path,style: "color: white",data: { turbolinks: false }  %></p>
</li>
</ul>
</div>
<div class="col-md-3">
<div class="narrow-phone" style="font-size: 16px;padding-bottom: 0;margin-top: -13px;text-align: right;">
<h5 class="mb-sm" style="color: #CCC; margin-bottom: 10px !important;font-size: 1em;font-weight: 600;letter-spacing: normal;line-height: 18px;margin: 0 0 14px 0;text-transform: uppercase;font-family: inherit;box-sizing: border-box;">Contact Us</h5>
<h5 class="mb-sm" style="color: #CCC; margin-bottom: 10px !important;font-size: 1em;font-weight: 600;letter-spacing: normal;line-height: 18px;margin: 0 0 14px 0;text-transform: uppercase;font-family: inherit;box-sizing: border-box;">Girish Nagar</h5>
<span class="phone" style="color: #FFF;font-weight: bold;display: block;">
<i class="fa fa-whatsapp" style="display: inline-block;font: normal normal normal 14px/1 FontAwesome;font-size: inherit;text-rendering: auto;box-sizing: border-box;"></i>
8827-047-626
</span>
</div>	
</div>
</div>	
</div>
<div class="footer-copyright">
<div class="container">
<div class="row" style="margin-bottom: 25px;">
<div class="col-md-12" align="center" style="width: 100%;float: left;position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px;">
<p class="h5" style="font-size: 14px;font-family: inherit;font-weight: 500;line-height: 1.1;">
<a href="#" style="color: #FFF;">roshnitents.com</a> © Copyright 2018. All Rights Reserved.Powered By: 
<a href="http://localhost:3000/homes/abouts" style="color: #FFF;"> Roshni Nagar</a>
</p>

</div>
</div>	
</div>
</div>

</footer>
</body>
</html>